name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tlint:
    name: Lint checks
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/trento-project/tlint:latest
      volumes:
        - ${{ github.workspace }}:/data
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run TLint
        run: "/home/tlint/tlint lint -f /data/checks"
